"""empty message

Revision ID: 556f71a6e4ac
Revises: 68c3fc433c79
Create Date: 2023-05-06 13:30:06.059323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556f71a6e4ac'
down_revision = '68c3fc433c79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_mascot', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('team_mascot')

    # ### end Alembic commands ###