"""empty message

Revision ID: 3ef50c16db12
Revises: 556f71a6e4ac
Create Date: 2023-05-06 13:30:22.682378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef50c16db12'
down_revision = '556f71a6e4ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('team_mascot')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_mascot', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###