"""empty message

Revision ID: 68c3fc433c79
Revises: 54bfbf7d9c01
Create Date: 2023-05-06 13:28:48.860688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c3fc433c79'
down_revision = '54bfbf7d9c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('team_mascot')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_mascot', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###