"""empty message

Revision ID: 54bfbf7d9c01
Revises: b65efdd9529e
Create Date: 2023-05-06 13:27:16.133550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54bfbf7d9c01'
down_revision = 'b65efdd9529e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_mascot', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('team_mascot')

    # ### end Alembic commands ###